package com.ironhack.theBestMidtermProject.model.users;

import javax.persistence.*;

//An user can have three different roles: ACCOUNT_HOLDER, ADMIN and THIRD_PARTY. A role has its autogenerated and
// distinctive id, a name (this is ACCOUNT_HOLDER, ADMIN or THIRD_PARTY), and a variable pointing to the user.

@Entity
public class Role {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String name;

    @ManyToOne
    private User user;

//    Empty constructor
    public Role() {
    }

//    Constructor with all parameters
    public Role(String name, User user) {
        this.name = name;
        this.user = user;
    }

//    Getters and setters
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }
}
